
bdd1 <- read.csv('generated/words_presence.csv', header=T, sep=",")
colnames(bdd1)
bdd1$nuance<-as.factor(bdd1$nuance)
bdd1$region<-as.factor(bdd1$region)
bdd1$Lutte<-as.factor(bdd1$Lutte)
bdd1$Droite<-as.factor(bdd1$Droite)
bdd1$Gauche<-as.factor(bdd1$Gauche)
bdd1$Conduite<-as.factor(bdd1$Conduite)
bdd1$Ecologie<-as.factor(bdd1$Ecologie)
bdd1$Union<-as.factor(bdd1$Union)
bdd1$Construire<-as.factor(bdd1$Construire)
bdd1$Construisons<-as.factor(bdd1$Construisons)
bdd1$Juste<-as.factor(bdd1$Juste)
bdd1$Demain<-as.factor(bdd1$Demain)
bdd1$France<-as.factor(bdd1$France)
bdd1$Changer<-as.factor(bdd1$Changer)
bdd1$Union<-as.factor(bdd1$Union)
bdd1$Forte<-as.factor(bdd1$Forte)
bdd1$Force<-as.factor(bdd1$Force)
bdd1$Rassembler<-as.factor(bdd1$Rassembler)
bdd1$Action<-as.factor(bdd1$Action)
bdd1$Oser<-as.factor(bdd1$Oser)
bdd1$Osons<-as.factor(bdd1$Osons)
bdd1$Ensemble<-as.factor(bdd1$Ensemble)
bdd1$Tous<-as.factor(bdd1$Tous)
bdd1$Alliance<-as.factor(bdd1$Alliance)
bdd1$Progres<-as.factor(bdd1$Progres)
bdd1$Changement<-as.factor(bdd1$Changement)
bdd1$Rassemblement<-as.factor(bdd1$Rassemblement)
bdd1$Independant<-as.factor(bdd1$Independant)
bdd1$Tete<-as.factor(bdd1$Tete)
bdd1$Nouveau<-as.factor(bdd1$Nouveau)
bdd1$Soutenu<-as.factor(bdd1$Soutenu)
bdd1$Ecologiste<-as.factor(bdd1$Ecologiste)
bdd1$Front<-as.factor(bdd1$Front)
bdd1$Moderne<-as.factor(bdd1$Moderne)
bdd1$id<-str(bdd1$id)
bdd1$contient_nom_candidat<-as.factor(bdd1$contient_nom_candidat)
bdd1$Extreme<-as.factor(bdd1$Extreme)
bdd1$UMP<-as.factor(bdd1$UMP)
bdd1$Soutenue<-as.factor(bdd1$Soutenue)
bdd1$Solidaire<-as.factor(bdd1$Solidaire)
bdd1$PS<-as.factor(bdd1$PS)
bdd1$PC<-as.factor(bdd1$PC)
bdd1$Ouvriere<-as.factor(bdd1$Ouvriere)
bdd1$National<-as.factor(bdd1$National)
bdd1$Europe<-as.factor(bdd1$Europe)
bdd1$Centre<-as.factor(bdd1$Centre)
bdd1$Anticapitaliste<-as.factor(bdd1$Anticapitaliste)
bdd1$exclam<-as.factor(bdd1$exclam)
#rename "!"
names(bdd1)[names(bdd1)=="X."] <- "exclam"
bdd1$exclam<-as.factor(bdd1$exclam)
summary(bdd1)
colnames(bdd1)
#on enlève ceux qui n'ont pas d'intérêt
drops <- c("candidat","Construire","Moderne","Oser","Progres","Demain", "Tete")
bdd1<-bdd1[,!(names(bdd1) %in% drops)]


row.names(bdd1)<-bdd1$id
#ACM
colnames(bdd1)
colnames(bdd1[2:36])
bdd1 <- bdd1[2:36]
bdd1<-as.data.frame(bdd1)
res.mca = MCA(bdd1, quanti.sup=3, quali.sup=c(1,2))
cah<-HCPC(res.mca)

